### ISSUE TITLE
Update Nav menu and add Intro blurb

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/antibody-api#172]
Based on @emquardokus's feedback from https://github.com/hubmapconsortium/antibody-api/issues/166#issuecomment-2083037998

>It would also be great to have an introduction to what the AVR website is for which many have asked or have misinterpreted based on interactions at several meetings or in discussions with TMCs. 
>Another important change would be the ADD AVRs since this is limited not to everyone and should continue to be so reviews can occur prior to adding AVRs.
>Some suggestions we had:
>* "Add AVRs" hyperlink currently directs to Globus. May want to change to avoid people trying to submit through Globus!
>* Could link something like "Learn more about AVRs at ARWG" and hyperlink to https://hubmapconsortium.org/open-working-groups/
>* Could link "AVR SOP" with hyperlink https://zenodo.org/doi/10.5281/zenodo.7418623, which will not change even as we publish new versions of SOP  
><img width="1878" alt="image001" src="https://github.com/hubmapconsortium/antibody-api/assets/47257000/1a2a43ca-f6ce-4d5b-993e-402b4f0cd6ae">

## Update the nav items and add intro blurb as shown in the below mockup:
<img width="1293" alt="Screenshot 2024-05-02 at 1 59 15 PM" src="https://github.com/hubmapconsortium/antibody-api/assets/195873/3d4d9ade-cf35-4120-b6b2-b9c739cd0657">

**Comment by yuanzhou** [comment]
@emquardokus we are including your request to the upcoming sprint, can you send an introduction paragraph about AVR? Can you also take a look at the mockup and see if everything gets reflected?

**Comment by emquardokus** [comment]
@yuanzhou we would like to use this paragraph to introduce AVRs on the AVR website; it comes from our SOP.

**Comment by yuanzhou** [comment]
@emquardokus two things to confirm:
- Do you still want to keep "AVR SOP" link in the top menu? As shown in the mockup.
- How do you prefer to handle the "Add AVRs" or just remove it?

**Comment by emquardokus** [comment]
@yuanzhou @shirey 
1) AVR SOP and AVR FAQ should both be linked from top menu
2) Need to have meeting to discuss---Add AVRs has a complicated history--we don't want the button as prominent and confusing to researchers as the process was changed 100% for how this works compared to v1.0 version of Website---this might be better to schedule a meeting to walk through since the way we really want this to go ultimately is to submit for review rather than submit to immediately go live by original authors.  The Affnity reagents working group (ARWG) folks would review the AVRs, comment, revisions would be made and the final versions would be uploaded by us to go live.
It used to immediately go live to AVR website and quality was poor at best with no standardization until ARWG set up a process.  Right now we collect everything via google sheets, review, author revise, we finalize and upload.
3) Noticed a problem in the header paragraph due to the change in process that needs to be corrected, but is dependent on conversation in 2) above.
This section  of paragraph needs to be fixed as it does not reflect the new process. 
**"This AVR metadata is included in a .CSV file uploaded to the portal by the contributing author for all AVRs submitted at one time. The AVR is completed as a text file and saved as a PDF for submission to the HuBMAP AVR upload site; it contains additional characterization data. "**

**Comment by yuanzhou** [comment]
@emquardokus would it be Okay if we remove the text from the first paragraph, for now? Once you have settled on the No.2 question, we'll update.
>This AVR metadata is included in a .CSV file uploaded to the portal by the contributing author for all AVRs submitted at one time. The AVR is completed as a text file and saved as a PDF for submission to the HuBMAP AVR upload site; it contains additional characterization data.

**Comment by yuanzhou** [comment]
We've added the "AVR SOP" and "About AVRs ar ARWG" links on AVR. Due to the pending discussion on "What is AVR" blurbs and the "Add AVRs" link, a separate issue will need to created later once they are finalized.
<img width="812" alt="Screenshot 2024-09-30 at 12 06 15 PM" src="https://github.com/user-attachments/assets/2eb1c38d-7cb5-4bad-b5b7-32b7c2a50741">
